version: '3.8'
name: mongodb-dev
services:
  biller-mongodb-dev:
    container_name: biller-mongo-dev-container
    image: mongo:7.0.6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEFAULT_USERNAME_DEV}
      MONGO_INITDB_ROOT_PASSWORD: ${DEFAULT_PASSWORD_DEV}
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - kravatar-dev-network

  biller-mongo-express-dev:
    container_name: biller-mongo-express-dev-container
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: biller-mongo-dev-container
      ME_CONFIG_BASICAUTH_USERNAME: ${DEFAULT_USERNAME_DEV}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DEFAULT_PASSWORD_DEV}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEFAULT_USERNAME_DEV}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEFAULT_PASSWORD_DEV}
    depends_on:
      - biller-mongodb-dev
    restart: unless-stopped
    networks:
      - kravatar-dev-network

networks:
  kravatar-dev-network:
    driver: bridge

volumes:
  data:
